log_level: DEBUG
client_auth_oid: 1.3.6.1.4.1.64609.1.1
known_rdis:
  - bonares
  - edal
gitlab_api:
    url: https://datahub-dev.ipk-gatersleben.de
    group: FAIRagro-advanced-middleware-integration-tests
