apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fairagro-advanced-middleware-api-chart.fullname" . }}
  labels:
    {{- include "fairagro-advanced-middleware-api-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fairagro-advanced-middleware-api-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-secret.yaml") . | sha256sum }}
        {{- with .Values.api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "fairagro-advanced-middleware-api-chart.labels" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fairagro-advanced-middleware-api-chart.serviceAccountName" . }}
      {{- with .Values.api.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.couchdb.enabled }}
      initContainers:
        - name: setup-couchdb
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command: ["/api/middleware-api/middleware-api", "setup-couchdb"]
          env:
            - name: MIDDLEWARE_API_CONFIG
              value: /run/secrets/middleware-api-config
            {{- include "fairagro-advanced-middleware-api-chart.couchdbEnvVars" . | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /run/secrets/middleware-api-config
              readOnly: true
              subPath: middleware-api-config
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.api.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command:
            - /api/middleware-api/middleware-api
            - "--host"
            - "0.0.0.0"
            - "--port"
            - {{ .Values.api.service.port | quote }}
            - "--workers"
            - {{ .Values.api.workers | quote }}
          env:
            - name: CELERY_BROKER_URL
              value: {{ include "fairagro-advanced-middleware-api-chart.celeryBrokerUrl" . | quote }}
            - name: CELERY_RESULT_BACKEND
              value: {{ include "fairagro-advanced-middleware-api-chart.celeryResultBackend" . | quote }}
            {{- include "fairagro-advanced-middleware-api-chart.couchdbEnvVars" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port | int }}
              protocol: TCP
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /run/secrets/middleware-api-config
              readOnly: true
              subPath: middleware-api-config
            {{- with .Values.api.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "fairagro-advanced-middleware-api-chart.fullname" . }}-config
            items:
              - key: middleware-api-config
                path: middleware-api-config
        {{- with .Values.api.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
