{{- if .Values.api.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fairagro-advanced-middleware-api-chart.fullname" . }}
  labels:
    {{- include "fairagro-advanced-middleware-api-chart.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.api.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.api.ingress.mtlsEnabled }}
    nginx.ingress.kubernetes.io/auth-tls-secret: "{{ .Release.Namespace }}/{{ include "fairagro-advanced-middleware-api-chart.caTlsSecretName" . }}"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "{{ .Values.api.ingress.mtlsVerifyDepth }}"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    {{- end }}
spec:
  {{- with .Values.api.ingress.className }}
  ingressClassName: {{ . }}
  {{- else }}
  ingressClassName: nginx
  {{- end }}
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- range .Values.api.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ include "fairagro-advanced-middleware-api-chart.fullname" $ }}-{{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "fairagro-advanced-middleware-api-chart.fullname" $ }}
                port:
                  number: {{ $.Values.api.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
