log_level: DEBUG

db_name: edaphobase
db_user: postgres
db_password: ~
db_host: postgres  # Docker service name

rdi: edaphobase
batch_size: "10"

api_client:
  api_url: "http://middleware-api:8000"
  client_cert_path: null
  client_key_path: null
